# Generated by Django 5.1.1 on 2024-10-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('category', models.CharField(choices=[('J', 'JACKET'), ('S', 'SHOE')], max_length=1)),
            ],
        ),
    ]
